language: python
python:
  - "2.7"
  - "3.3"
before_install:
  # install gsl
  - sudo apt-get install libgsl0-dev
  # use Anaconda to get compiled versions of scipy and numpy,
  # modified from https://gist.github.com/dan-blanchard/7045057
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip scikit-learn numpy Cython scipy nose futures
  - source activate env_name

  # use ``pip install .`` rather than ``python setup.py install`` due to travis log limits
  - pip install .

script: JOBLIB_MULTIPROCESSING=0 nosetests -w /tmp horizont.tests
